# Adapted from https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Install z3
        run: |
          sudo apt-get update
          sudo apt-get install z3
      - name: Build and Test
        run: sbt -v +test